//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TroyStevens.Market.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ThirdPartyProcessingDelayInMilliseconds {
            get {
                return ((int)(this["ThirdPartyProcessingDelayInMilliseconds"]));
            }
            set {
                this["ThirdPartyProcessingDelayInMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAA,BBB,CCC,DDD,EEE,FFF,BBB,EEE,AAA,DDD,AAA,CCC")]
        public string CommaSeperatedProviderSymbolsOrion {
            get {
                return ((string)(this["CommaSeperatedProviderSymbolsOrion"]));
            }
            set {
                this["CommaSeperatedProviderSymbolsOrion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAA,BBB,CCC,GGG,HHH,III,JJJ,BBB,GGG,AAA,III,CCC")]
        public string CommaSeperatedProviderSymbolsPolaris {
            get {
                return ((string)(this["CommaSeperatedProviderSymbolsPolaris"]));
            }
            set {
                this["CommaSeperatedProviderSymbolsPolaris"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsThirdPartyProcessingDelayActive {
            get {
                return ((bool)(this["IsThirdPartyProcessingDelayActive"]));
            }
            set {
                this["IsThirdPartyProcessingDelayActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MaxiumNumberOfSymbolBots {
            get {
                return ((int)(this["MaxiumNumberOfSymbolBots"]));
            }
            set {
                this["MaxiumNumberOfSymbolBots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MaxNumberOfSymbolUpdates {
            get {
                return ((int)(this["MaxNumberOfSymbolUpdates"]));
            }
            set {
                this["MaxNumberOfSymbolUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15000")]
        public int ProviderInactivtyTimeOutInMilliseconds {
            get {
                return ((int)(this["ProviderInactivtyTimeOutInMilliseconds"]));
            }
            set {
                this["ProviderInactivtyTimeOutInMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoggingFeatureEnabled {
            get {
                return ((bool)(this["LoggingFeatureEnabled"]));
            }
            set {
                this["LoggingFeatureEnabled"] = value;
            }
        }
    }
}
